.. _data_type_hierarchy:

Type Hierarchy
--------------

* :ref:`Container <sec-Container>`

   * :ref:`DynamicTable <sec-DynamicTable>`

      * :ref:`PlaneSegmentation <sec-PlaneSegmentation>`
   * :ref:`NWBContainer <sec-NWBContainer>`

      * :ref:`Device <sec-Device>`
      * :ref:`ImagingPlane <sec-ImagingPlane>`
      * :ref:`NWBDataInterface <sec-NWBDataInterface>`

         * :ref:`ImageSegmentation <sec-ImageSegmentation>`

            * :ref:`EXTRACTSegmentation <sec-EXTRACTSegmentation>`
         * :ref:`TimeSeries <sec-TimeSeries>`

            * :ref:`ImageSeries <sec-ImageSeries>`
      * :ref:`OpticalChannel <sec-OpticalChannel>`
* :ref:`Data <sec-Data>`

   * :ref:`ElementIdentifiers <sec-ElementIdentifiers>`
   * :ref:`VectorData <sec-VectorData>`

      * :ref:`VectorIndex <sec-VectorIndex>`


