**Source Specification:** see :numref:`hdmf-type-namespace-src` 
 
.. _hdmf-type-namespace-src:

ndx-extract
-----------

**Description:** see :numref:`hdmf-type-namespace-doc`

**YAML Specification:**

.. code-block:: yaml
    :linenos:

    author:
    - Cesar Echavarria
    contact:
    - cesar.echavarria@catalystneuro.com
    doc: NWB:N Extension for storage of EXTRACT parameters and output
    name: ndx-extract
    schema:
    - namespace: core
      neurodata_types:
      - ImageSegmentation
    - source: ndx-extract.extensions.yaml
    version: 0.1.1


