Format Overview
===============

.. _hdmf-type-namespace-doc:

ndx-extract
-----------

- **Description:** NWB:N Extension for storage of EXTRACT parameters and output
- **Name:** ndx-extract
- **Version:** 0.1.1
- **Authors:**
    - Cesar Echavarria

- **Contacts:**
    - cesar.echavarria@catalystneuro.com

- **Schema:**
    - **namespace:** core 
    - **neurodata_types:** ['ImageSegmentation'] 
    - **source:** ndx-extract.extensions.yaml 


.. only:: html 

    .. include:: _format_auto_docs/format_spec_type_hierarchy.inc

